### ISSUE TITLE
Deprecation Notice on Wallet

### ISSUE THREAD

**Issue by AngelMunoz** [xpring-eng/Xpring-JS#1074]
Hello there, I've been playing with the Xpring-JS library and I find it quite neat to use and really simple to comprehend kudos on that

I also found out that there's a deprecation notice that vscode is warning me about about Wallet methods are deprecated
![image](https://user-images.githubusercontent.com/8684875/107888802-dff93600-6ecb-11eb-83b4-ef98e20b54be.png)

however I was not able to import the WalletFactory from the package

![image](https://user-images.githubusercontent.com/8684875/107888808-f0a9ac00-6ecb-11eb-9ffa-09a0024942fd.png)

I was able to figure out that the mentioned class is inside the [common library](https://github.com/xpring-eng/xpring-common-js) ibut it says in the readme that is not meant to consume directly

is it safe to pull the common library or should I wait for the sdk to pull the wallet factory from there?

I'm using 
- `"xpring-js": "^5.3.1"`
- node `v14.15.4` 
- Windows 10

**Comment by intelliot** [comment]
This SDK has been replaced with [xrpl.js](https://github.com/XRPLF/xrpl.js). [Get started here](https://xrpl.org/get-started-using-javascript.html).
