### ISSUE TITLE
How to make this library work in the browser?

### ISSUE THREAD

**Issue by Falx** [xpring-eng/Xpring-JS#1105]
Hi, I tried shimming everything as in your example webpack.config.js but i still get this runtime error:

![image](https://user-images.githubusercontent.com/1684858/121205251-c9f6f300-c877-11eb-8e1c-e1067d637fbc.png)

Do you have any idea which http2 module I can use to shim/replace the http2 node module?

**Comment by intelliot** [comment]
This SDK has been replaced with [xrpl.js](https://github.com/XRPLF/xrpl.js)
