### ISSUE TITLE
Question: Are there contributing guidelines anywhere for this repo?

### ISSUE THREAD

**Issue by vaelinn123** [xpring-eng/Xpring-JS#22]
Apologies if it is documented somewhere and I have overlooked, feel free to redirect me to a more appropriate spot to ask this question if there is one. I am assuming that PR's are welcome.

Thanks!

**Comment by keefertaylor** [comment]
We'd love contributions from the community to this project!

We're still working on developing exact guidelines, but in general we're looking for unit tested code that passes our linter.

**Comment by vaelinn123** [comment]
Awesome, thanks!

**Comment by keefertaylor** [comment]
I'm working on building up some guidelines on this stuff. I'm starting with the lowest level of dependencies in the Xpring SDK, and then I'll propagate these changes up to this level shortly. 

Feel free to comment if you have thoughts: https://github.com/xpring-eng/xpring-common-protocol-buffers/pull/10

**Comment by keefertaylor** [comment]
I added a contributors section to Xpring-Common-JS this morning:
https://github.com/xpring-eng/xpring-common-js/pull/46

Once that gets onced over I'll plan to propagate that here.

**Comment by keefertaylor** [comment]
Fixed, please see CONTRIBUTING.md.
