### ISSUE TITLE
Change IlpClient.sendPayment API names

### ISSUE THREAD

**Issue by nkramer44** [xpring-eng/Xpring-JS#227]
First, we should align Xpring-JS with the other sdks by changing the `IlpClient.send` API to `IlpClient.sendPayment`.

Second, we should change the second parameter of that API from `paymentPointer` to `destinationPaymentPointer`, and change `sender` to `senderAccountId`

API should be:
```ts
sendPayment(
    amount: BigInteger | number | string,
    destinationPaymentPointer: string,
    senderAccountId: string,
    bearerToken?: string,
  ): Promise<SendPaymentResponse>
```

**Comment by intelliot** [comment]
This SDK has been deprecated. For those finding this issue in the future, you can find ILP-related projects at https://github.com/interledgerjs
