### ISSUE TITLE
Prepend "Bearer " to auth token for ILP API

### ISSUE THREAD

**Issue by nkramer44** [xpring-eng/Xpring-JS#228]
This won't change anything functionally, but in order to abide by correct standards, the ILP SDK should add `Bearer ` to the beginning of all auth tokens, if they do not already have them.

Similarly, we should wrap `bearerToken` in a class called `IlpCallCredentials`, which will do this for us and make the bearer token more strongly typed.

**Comment by intelliot** [comment]
This SDK has been deprecated. For those finding this issue in the future, you can find ILP-related projects at https://github.com/interledgerjs
