### ISSUE TITLE
Missing destination tag functionality

### ISSUE THREAD

**Issue by schenkty** [xpring-eng/Xpring-JS#25]
There is no method to send a payment to a destination tag if needed

**Comment by keefertaylor** [comment]
Feature request noted. Thanks for the feedback. 

Functionality to support this will be supported through X-address formats (https://xrpaddress.info/). This functionality is in flight to land in core sometime later today and will appear here shortly afterwards. Here's the PR to follow: https://github.com/xpring-eng/xpring-common-js/pull/43.

This is pretty high priority for us.

**Comment by schenkty** [comment]
Thank you, I look forward to seeing this functionality.

**Comment by keefertaylor** [comment]
Apologies that this took so long. 

I cut and published version 1.1.0 of this library. Documentation is updated as well. 

We don't provide an explicit API for destination tag, but we do support the X-Address format, which lets you encode an X-Address from a classic (starts with 'r') address and a tag. 

You'll probably want to look at `encodeXAddress` in `Utils` to formulate X-Addresses. 

I realize that it is a bit weird that a `destinationTag` argument wasn't added to send. As an ecosystem, we'd like to push folks towards using X-Addresses which tends to eliminate user errors when working with tags.
