### ISSUE TITLE
network client functionality does not work

### ISSUE THREAD

**Issue by schenkty** [xpring-eng/Xpring-JS#26]
I am unable to properly use the network client. It appears tests are based on a fake network client which allows this issue to pass through. I would recommend that all tests use an active network client connected to the test net

**Comment by keefertaylor** [comment]
You actually probably don't want to construct your Xpring Client with that constructor.  Instead, use the static factory method: 
```
const remoteURL = "grpc.xpring.tech:80";
const xpringClient = XpringClient.xpringClientWithEndpoint(remoteURL);
```

Apologies if you looked at an early version of our documentation, as this was initially spelled out wrong. This is also noted on the [constructor's documentation](https://github.com/xpring-eng/Xpring-JS/blob/master/src/xpring-client.ts#L43). If you feel like there's a way to make this more clear, LMK. 

---- 
A more detailed explanation of why this API exists:

We want our unit tests to be hermetic (ie. the only thing that causes test failures are the code under test itself, not external factors). Connecting unit tests to a live network violates this principle. 

To get around this, we fake the network layer by isolating and encapsulating network functionality, then injecting it into the class as a parameter. This allows us to fake the network interactions, while testing our business logic. 

There are two factors in TypeScript that make this hard:
- constructors cannot have visibility reduced with access modifiers (ie. all constructors are `public`)
- there can only be one constructor

This combination of factors means that the constructor *must* be what we want injected into the class, and we *can't* stop clients from trying to use it. This is, AFAICT, a fundamental limitation of TypeScript that doesn't exist in other languages (in Swift or Java, we'd overload the constructors and mark one as `private`). 

There's probably some other way to do this injection if we really wanted to (something hacky to read parameters out of global state perhaps) but I think that's less clear. Open to suggestions that aren't too magical. 

Note that you could, in fact, construct a working `XpringClient` using the constructor, it just takes more binding (This is in fact what the static factory method is doing):

```
const remoteURL = "grpc.xpring.tech:80";
const grpcClient = new GRPCNetworkClient(remoteURL);
const xpringClient = new XpringClient(grpcClient);
```

Lastly, to your point about not using a faked network client, there are [integration tests](https://github.com/xpring-eng/Xpring-JS/blob/master/test/integration-test.ts) which do in fact run this against a live test network. These tests are not hermetic. If they prove flaky, I may move them off the critical development path.

**Comment by schenkty** [comment]
Thank you for this clarification. I certainly was looking at early docs as I had a concept up and running on release day last week

**Comment by keefertaylor** [comment]
Sorry about that. Glad you're on your way now!

(Feel free to re-open if you need anything else)
