### ISSUE TITLE
[PayID] xrpAddressForPayID resolves mainnet address as testnet T-address

### ISSUE THREAD

**Issue by gnurag** [xpring-eng/Xpring-JS#552]
I'm testing PayID resolution using `Xpring-SDK-Demo/node/src/index-payid.js` with `pay$rabbitkick.club` as example:

```
$ curl --header 'PayID-Version: 1.0' --header 'Accept: application/xrpl-mainnet+json' 'https://rabbitkick.club/pay'
{
  "addresses": [
    {
      "paymentNetwork": "XRPL",
      "environment": "MAINNET",
      "addressDetailsType": "CryptoAddressDetails",
      "addressDetails": {
        "address": "rabbitZWLG8PptsrPjuvKX4uAGjS5B64PP"
      }
    }
  ]
}

```
Looking at the above response, `xrpAddressForPayID("pay$rabbitkick.club")` should resolve to a mainnet address `X7m8Yc9tJQKkQzbNJFzoXCSYJ6bFyc2EuwwQLr6Nw6szAB8`, but it resolves to `T76Jx5J1wM1miWMq2dj2RCUS893dVUNHiLfidgvkmK8mYk9` instead.

**Current result**
`T76Jx5J1wM1miWMq2dj2RCUS893dVUNHiLfidgvkmK8mYk9`

**Expected result:**
`X7m8Yc9tJQKkQzbNJFzoXCSYJ6bFyc2EuwwQLr6Nw6szAB8` or `rabbitZWLG8PptsrPjuvKX4uAGjS5B64PP`

**Comment by gnurag** [comment]
Also happens with Gatehub PayIDs - `user$payid.gatehub.net` returns a T-address.

**Comment by intelliot** [comment]
This SDK has been deprecated. For issues related to PayString, see https://github.com/PayString
