### ISSUE TITLE
(node:3568) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: account not found

### ISSUE THREAD

**Issue by noahwalugembe** [xpring-eng/Xpring-JS#573]
i got a test id from pay id
{ account: 'rDk7FQvkQxQQNGTtfM2Fr66s7Nm3k87vdS', tag: 123 }
and then converted it to ('XVBaSqtX9tRVDVPB4eoc2F6nm664PS5ZH5XLovxzvT6qBEh')
but when i send mony on that test addres i get this error
(node:3568) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: account not found
I need help

**Comment by intelliot** [comment]
This SDK has been replaced with [xrpl.js](https://github.com/XRPLF/xrpl.js). If an account does not exist on the ledger, you can create it by sending it a payment of at least the [base reserve](https://xrpl.org/reserves.html).
