### ISSUE TITLE
How to send from a classic address

### ISSUE THREAD

**Issue by cjcobb23** [xpring-eng/Xpring-JS#707]
I'm looking for a way to send xrp from a classic address, but it seems like `send()` requires the sender to be a wallet. Maybe I am missing something.

**Comment by intelliot** [comment]
This SDK has been replaced with [xrpl.js](https://github.com/XRPLF/xrpl.js). For those finding this issue in the future, here's a way to send XRP: https://xrpl.org/send-xrp.html
