### ISSUE TITLE
encodeXAddress and decodeXAddress are not functions

### ISSUE THREAD

**Issue by cjcobb23** [xpring-eng/Xpring-JS#708]
If I run `Utils.encodeXAddress()` or `Utils.decodeXAddress()`, I get an error:  `TypeError: Utils.encodeXAddress is not a function`

**Comment by ExciteNG** [comment]
How far, fixed yet?

**Comment by intelliot** [comment]
This SDK has been replaced with [xrpl.js](https://github.com/XRPLF/xrpl.js). For those finding this issue in the future, some of the functions here may be helpful: https://js.xrpl.org/modules.html#classicAddressToXAddress
